config/routes.rb
Etsydemo::Application.routes.draw do
  
  devise_for :users

  get '/private' => 'private#index', as: 'user_root'

  get '/pricing' => 'public#prices', as: 'pricing'
  get '/faq' => 'public#faq', as: "faq"
  get '/support' => 'public#support'
  get 'private' => 'private#index'
  get 'private/settings' => 'private#settings'
  get '/contact' => 'pages#contact', as: "contact" 
  get '/about' => 'public#about', as: "about"
  get '/terms' => 'public#terms', as: "terms"
  get '/settings' => 'public#settings', as: "settings"
  get "pages/about"
  get "pages/contact"

  root 'public#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/private_controller.rb
class PrivateController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end

  def settings
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
	#layout 'landing'
	layout :resolve_layout

  def index
    if user_signed_in?
      redirect_to (private_path)
    else
      render "index"
    end
  end

  def prices

  end

  def faq

  end

  def support

  end

  def terms

  end

  def about
    
  end
  def settings
    
  end

  def resolve_layout
    case action_name
    when "index"
      "landing"    
    else
      "application"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map {|msg| content_tag(:li, msg) }.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human)

		html = <<-HTML
		  <div class="bs-callout bs-callout-danger">
    		<h4>#{sentence}</h4>
    		#{messages}
  		  </div>
		HTML

		html.html_safe
	end
end

app/helpers/private_helper.rb
module PrivateHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<div >
			<div class="padding footer-top-line">				
				<ul>
					<li><a href="/about">О нас</a></li>
					<li><a href="/terms">Условия использования</a></li>
					<li><a href="/settings">Настройки</a></li>
					<li><a href="/locale">English version</a></li>
					<!-- Go to www.addthis.com/dashboard to customize your tools -->
					<li><div class="addthis_sharing_toolbox"></div></li>
				</ul>
			</div>
			<div class="padding footer-bottom-line">				
				<ul>
					<li><a href="/settings">изменить IP адрес</a></li>
					<li><a href="/settings">скрыть IP адрес</a></li>
					<li><a href="/settings">vpn сервис</a></li>
					<li><a href="/about">анонимайзер для «вконтакте»</a></li>
					<li><a href="/terms">одноклассники</a></li>
					<li><a href="/settings">youtube</a></li>
					<li><a href="/settings">facebook</a></li>					
				</ul>
			</div>	
		</div>		
	</div>	
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
      <a class="navbar-brand" href="/private"><%= image_tag("logo.png", class: "bimage")%> SweetVPN</a>
      <% else %>
        <a class="navbar-brand" href="/"><%= image_tag("logo.png", class: "bimage")%> SweetVPN</a>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
              
        <li><%= link_to "Цены", pricing_path %></li>
        <li><%= link_to "Частые вопросы", faq_path %></li>
        <li><%= link_to "Поддержка", support_path %></li>
      </ul>      
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
        <p class="navbar-text">Вы вошли как: </p> 
         <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Редактировать профиль", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Выйти", destroy_user_session_path, method: :delete %></a></li>
          </ul>
        </li>         
        <% else %>
          <li><%= link_to "Войти", new_user_session_path %></li>
          <p class="navbar-text">|</p>
          <li><%= link_to "Регистрация", new_user_registration_path, class: "bold" %></li>          
        <% end %>       
        
      </ul>
    </div><!-- /.navbar-collapse -->


  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SweetVPN</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="root">
  <%= render 'layouts/header' %>
  <div class="container">
  	<div class="subheader"></div>

  	<% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg,:id => "flash_#{name}" %>
        </div>
      <%end %>
    <% end%>

	<%= yield %>
  
	</div>
<div class="root-footer"></div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SweetVPN - vpn service and anonymizer for FREE</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="root">
  <%= render 'layouts/header' %>
  <%= render 'layouts/public/hero' %>
  <%= render 'layouts/public/features' %>
  <%= render 'layouts/public/platforms' %>
  <%#= render 'layouts/public/extra' %>
<div class="root-footer"></div>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to EtsyDemo!</h1>
<h2>EtsyDemo is an online marketplace for buying ans selling handmade goods.</h2>

app/views/pages/contact.html.erb
<h1>Email us at abc@etsydemo.com</h1>

app/views/private/index.html.erb
<h3>Личный кабинет</h3>
<h4>Аккаунт <%=current_user.email %></h4>
<p>Find me in app/views/private/index.html.erb</p>

<div class="col-md-3">
<p><a href="#">Панель управления</a></p>
<p><%= link_to "Настройка устройств", private_settings_path %></p>
<p><a href="#">Центр помощи</a></p>
<p><a href="#">Выйти</a></p>
</div>
<div class="col-md-9">
<p>Ваше имя: <%= current_user.email %></p>
<p>Ваш пароль: <%= current_user.encrypted_password %></p>

</div>

app/views/private/settings.html.erb
<h1>Private#settings</h1>
<p>Find me in app/views/private/settings.html.erb</p>